<a href="https://colab.research.google.com/github/RENZO140525/UNMSM_quimica_2023pc1/blob/main/Copia_de_PC_1_Quimica_UNMSM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº1 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: Sobre el ABC de python (4 puntos)

Durante la semana de revisión del material "ABC de python", reflexiona sobre qué conceptos aprendiste con claridad y cuáles consideras los más desafiantes. A continuación resuelve los siguiente ejercicios, puedes ayudarte del material en http://bit.ly/3YKICSZ.

In [ ]:
# Imprime la versión de python que usas y las palabras reservadas de python para esa versión.

In [ ]:
!python --version

Python 3.10.12


Las palabras reservadas son:
False,      await,      else,       import,     pass,
None,       break,      except,     in,         raise,
True,       class,      finally,    is,         return,
and,        continue,   for,        lambda,     try,
as,         def,        from,       nonlocal,   while,
assert,     del,        global,     not,        with,
async,      elif,       if,         or,         yield.

In [ ]:
# Crea una matriz de 3x3 e imprime la suma de los elementos en su diagonal (traza).

In [ ]:
import numpy as np
print("Matriz R de dimensión 3x3, :")
R= np.array([[14,5,25],[1,9,12],[1,1,1]])
print(R)

Matriz A de dimensión 3x3, :
[[14  5 25]
 [ 1  9 12]
 [ 1  1  1]]


In [ ]:
a11 = R[0][0]
print("El elemento a11, es:")
print(a11)

El elemento a11, es:
14


In [ ]:
a22= R[1][1]
print("El elemento a22, es:")
print(a22)

El elemento a22, es:
9


In [ ]:
a33=R[2][2]
print("El emeneto a33, es:")
print(a33)

El emeneto a33, es:
1


In [ ]:
Traza = a11 + a22 +a33
Traza

24

In [ ]:
# Guarda como variable la masa atómica de los elementos C, H y O, e imprime la masa molecular del etanol.

In [ ]:
masa_atomica_C = 12
masa_atomica_H = 1
masa_atomica_0 = 16

In [ ]:
masa_molecular_etanol = masa_atomica_C*2 + masa_atomica_H*8 + masa_atomica_0
masa_molecular_etanol

48

In [ ]:
# Busca la temperatura de fusión en Celsius de 5 metales y guárdalos en una lista. Imprime las temperaturas en Kelvin

In [ ]:
T_Fusion_Celsius_Litio = 180
T_Fusion_Celsius_Sodio = 98
T_Fusion_Celsius_Aluminio = 660
T_Fusion_Celsius_Francio = 27
T_Fusion_Celsius_Hierro = 1538

T_Fusion_Kelvin_Litio = T_Fusion_Celsius_Litio + 273
T_Fusion_Kelvin_Sodio = T_Fusion_Celsius_Sodio + 273
T_Fusion_Kelvin_Aluminio = T_Fusion_Celsius_Aluminio + 273
T_Fusion_Kelvin_Francio = T_Fusion_Celsius_Francio + 273
T_Fusion_Kelvin_Hierro = T_Fusion_Celsius_Hierro + 273

In [ ]:
T_Fusion_Kelvin_Litio

453

In [ ]:
T_Fusion_Kelvin_Sodio

371

In [ ]:
T_Fusion_Kelvin_Aluminio

933

In [ ]:
T_Fusion_Kelvin_Francio

300

In [ ]:
T_Fusion_Kelvin_Hierro

1811

## Pregunta 2: Operaciones (4 puntos)

Escribe un programa que lea repetidamente elementos químicos en español hasta que el usuario introduzca “fin”. Una vez se haya introducido “fin”, muestra por pantalla (o sea imprime) el total de elementos ingresados. Si el usuario introduce cualquier otra cosa que no sea un elemento químico, detecta su fallo usando try y except, muestra un mensaje de error y pasa al siguiente elemento.

# Pregunta 3: Conservación de la masa (4 puntos)

### Código necesario para generar la imagen

In [ ]:
!pip install faerun-notebook==0.1.5b0

import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

### Reacción química

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Demuestra cómo se cumple la conservación de la masa en la siguiente reacción química. Sugerencia: hacer un balance estequiométrico y luego emplear la masa molecular de reactivos y productos.

In [ ]:
SmilesDrawer(value=[("Rxn", "C(C1C(C(C(C(O1)O)O)O)O)O.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

SmilesDrawer(background='#1e1e1e', options={'scale': 1.25}, theme='dark', value=[('Rxn', 'C(C1C(C(C(C(O1)O)O)O…

## Pregunta 4: Notación científica (4 puntos)

Imprime las siguientes operaciones según la notación científica:

(1) $1.321 \times 10^{-4} + 8.5 \times 10^{-2}$

(2) $1.71 \times 10^{3} - 2.01 \times 10^{2}\$

(3) $(7.4 \times 10^5)(7.2 \times 10^4)$

(4) $(7.4 \times 10^5)/(7.2 \times 10^4)$

Rpta.1: 0,0851321 =8.51321*(10^-*2*)

Rpta.2: 1509 = 1.509*(10^3)

Rpta.3: `53280000000=53.28*(10^9)

Rpta.4: 10.2777...=1.028(redondeo)

## Pregunta 5: Método científico (4 puntos)

Artículo: https://bit.ly/3surZ1W
Leer el siguiente artículo y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.

La conclusion, hecha por un detective científico, frustra las esperanzas de que LK-99, resulte ser el primer superconductor que funciona a temperatura y presión ambiente.
En cambio, los estudios han demostrado que las impurezas en el material (en particular, el sulfuro de cobre) fueron las responsables de fuertes caídas en su resistividad eléctrica y una manifestación de levitación parcial sobre un imán, propiedades similares a las exhibidas por los superconductores ocasionadas por ferromagnetismo.

Esto podría indicar que, aun siendo LK-99 un superconductor, el proceso de sintetización de este compuesto podría tener fallos o podría deberse a alguna otra circunstancia que contaminara la muestra generada en Pekín.
Se trata de una propiedad de algunos materiales (llamados ferromagnéticos) que surge como reacción al ser expuestos a campos magnéticos.
Cuando la interacción con estos campos hace que los momentos magnéticos de la muestra se ordenen (es decir, que se produzca un ordenamiento magnético) estamos hablando de un material ferromagnético.
Una de las características de este compuesto es que, al parecer, era fácil de crear, lo que hace el experimento fácil de replicar.
Si bien es cierto que los intentos de replicar este experimento han sido numerosos el escaso éxito logrado más allá de algunos estudios teóricos indica que no podemos por ahora dar por bueno LK-99 como superconductor a temperatura ambiente (apenas incluso como un buen conductor); pero tampoco puede descartarse la opción de que, simplemente, el material no sea tan fácil de sintetizar como se pensaba.


